/**
 * Host half of the high-school mathematics thinking-teacher plugin.
 *
 * @module dsh-math-thinking-teacher
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { homedir } from 'node:os'
import { join } from 'node:path'
import type { Context } from '@deepseek-ai/cordis'
import type {} from '@deepseek-ai/dsh-agent-presets'
import type {} from '@deepseek-ai/dsh-host-webserver'
import { assertPresetId, Config as ConfigSchema, type Config as TeacherConfig } from './config.ts'

/** Global shared with the Web client bundle. */
export const MATH_TEACHER_GLOBAL = '__NINGBO_DSH_MATH_THINKING_TEACHER__'

export const Config = ConfigSchema
export { assertPresetId }
export type { MathProblem } from './config.ts'

/** Required host services. */
export const inject = ['webServer', 'agentPresets']

const MANAGED_PRESET_MARKER = '# Managed by dsh-math-thinking-teacher. Do not edit this file.'

/** Resolve the user preset root shared by the installed DSH profile. */
function userPresetRoot(): string {
  return join(process.env.DSH_HOME ?? join(homedir(), '.dsh'), '.agent-presets')
}

/** Render the one-row agent composition required by the selected mathematics sessions. */
export function renderPreset(config: TeacherConfig): string {
  return `${MANAGED_PRESET_MARKER}\n- id: math-thinking-teacher-policy\n  name: dsh-math-thinking-teacher/preset\n  inject: [systemPrompt]\n  config: ${JSON.stringify(config)}\n`
}

/** Render the display metadata paired with the generated preset composition. */
function renderPresetMetadata(config: TeacherConfig): string {
  return `${MANAGED_PRESET_MARKER}\nname: ${JSON.stringify(config.teacherName)}\ndescription: "高考数学思维训练：诊断、追问与最小提示。"\norder: 20\n`
}

/** Write this plugin's preset without overwriting a user-owned composition. */
export async function ensurePreset(config: TeacherConfig, root = userPresetRoot()): Promise<void> {
  assertPresetId(config.presetId)
  const directory = join(root, config.presetId)
  await mkdir(directory, { recursive: true, mode: 0o700 })
  const composition = join(directory, 'agent.cordis.yml')
  const metadata = join(directory, 'preset.yml')
  for (const [path, content] of [[composition, renderPreset(config)], [metadata, renderPresetMetadata(config)]] as const) {
    try {
      const existing = await readFile(path, 'utf8')
      if (!existing.startsWith(MANAGED_PRESET_MARKER)) {
        throw new Error(`dsh-math-thinking-teacher: presetId "${config.presetId}" is already owned by ${path}`)
      }
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
    }
    await writeFile(path, content, { encoding: 'utf8', mode: 0o600 })
  }
}

/** Publish browser-safe configuration and make the dedicated preset discoverable. */
export async function apply(ctx: Context, config: TeacherConfig): Promise<void> {
  await ensurePreset(config)
  const known = await ctx.agentPresets.list()
  if (!known.some(preset => preset.id === config.presetId && preset.broken === undefined)) {
    throw new Error(`dsh-math-thinking-teacher: generated preset "${config.presetId}" is not discoverable; enable dsh-agent-presets includeUserRoot`)
  }
  ctx.on('webserver/index-inject', (table) => {
    table.push({ kind: 'global', name: MATH_TEACHER_GLOBAL, value: config })
  })
}
